# Generated by Django 2.0.8 on 2018-10-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='offer_id',
        ),
        migrations.AddField(
            model_name='offer',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
