# Generated by Django 2.0.8 on 2018-10-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ses', '0002_battery_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumptionRate',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('users_firstName', models.CharField(max_length=50)),
                ('users_lastName', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Username',
        ),
    ]
