# Generated by Django 2.0.8 on 2018-10-03 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ses', '0002_battery_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Username',
        ),
    ]
