# Generated by Django 2.0.8 on 2018-10-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ses', '0002_auto_20181016_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('productionrate', models.IntegerField()),
                ('consumptionrate', models.IntegerField()),
                ('stoves', models.IntegerField()),
                ('lights', models.IntegerField()),
                ('household_appliances', models.IntegerField()),
                ('home_entertainment', models.IntegerField()),
                ('solar_panels', models.IntegerField()),
            ],
        ),
    ]
