# Generated by Django 2.0.8 on 2018-10-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ses', '0003_energy'),
    ]

    operations = [
        migrations.AddField(
            model_name='energy',
            name='windmills',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
