# Generated by Django 2.0.8 on 2018-10-15 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ses', '0003_auto_20181007_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='money',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ses.Money'),
            preserve_default=False,
        ),
    ]
