# Generated by Django 2.0.8 on 2018-10-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ses', '0004_household_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
