# Generated by Django 2.0.8 on 2018-10-15 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ses', '0006_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='ID',
            new_name='user_id',
        ),
    ]
