# Generated by Django 2.0.8 on 2018-10-16 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ses', '0007_auto_20181015_2325'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
