version: '3'

services:

  django:
    build: ./backend/src
    command: ["python3", "manage.py", "runserver"]

    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    command: ["npm", "start"]

    ports:
      - "3000:3000"

